apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mw-auto-injector-tls
  namespace: mw-autoinstrumentation
spec:
  dnsNames:
    - mw-auto-injector.mw-autoinstrumentation.svc
    - mw-auto-injector.mw-autoinstrumentation.svc.DOMAIN_NAME
  issuerRef:
    kind: Issuer
    name: mw-auto-injector-selfsigned
  secretName: mw-auto-injector-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mw-auto-injector-selfsigned
  namespace: mw-autoinstrumentation
spec:
  selfSigned: {}